name: "IaC CI/CD Pipeline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    name: "Terraform Lint & Validation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Verificar Formato (terraform fmt)
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Inicializar Terraform
        run: terraform init -backend=false
        working-directory: ./terraform

      - name: Validar Sintaxis (terraform validate)
        run: terraform validate
        working-directory: ./terraform